Controllers/TagController.cs, client/src/components/ApplicationViews.jsx, client/src/components/NavBar.jsx, client/src/components/tags/TagsList.jsx, client/src/managers/tagManager.js
- created Tag Management option on Navbar
- created `TagController.cs` page with controller to get all Tags and order alphabetically
- created a `Taglist.jsx` page to render on browser
- created `TagManager.jsx` with a fetch for endpoint
=> view all tags alphabetically

Controllers/TagController.cs, client/src/components/ApplicationViews.jsx, client/src/components/tags/CreateTag.jsx, client/src/components/tags/TagsList.jsx, client/src/managers/tagManager.js
- Created Tag button
- Created form in which user can enter a new Tag name
- Created Save button
-  Confirmed data saves to db
=> Ft/create atag/rob

Controllers/PostController.cs, Models/DTOs/PostDTO.cs, client/src/components/posts/NewPost.jsx
- Added to post backend to return tags associated with the posts.
- Added tags list selection for the new post component
=> Posttags for posts/kayceb

client/src/components/ApplicationViews.jsx, client/src/components/NavBar.jsx, client/src/components/posts/CommentDetail.jsx
=> Fixed NavBar issue and Category linking issue

Controllers/ReactionController.cs, client/src/components/posts/PostDetails.css, client/src/components/posts/PostDetails.jsx, client/src/managers/reactionManager.js
- Implemented render of reactions of post and their respective count
=> Ft/view reactions on post/ezjbrewer

Controllers/PostController.cs, client/src/components/ApplicationViews.jsx, client/src/components/Home.css, client/src/components/Home.jsx, client/src/managers/postManager.js
- Home.jsx component added with a Home.css as well.
- Added a controller endpoint to return all posts where the user is subscribed
=> Home.jsx added that displays the list of user subscribed posts

Controllers/ReactionPostController.cs, client/src/components/posts/PostDetails.jsx, client/src/managers/reactionManager.js, client/src/managers/reactionPostManager.js
- User now has ability to add/remove reaction
=> Ft/add a reaction/ezjbrewer

Controllers/PostController.cs, client/src/components/ApplicationViews.jsx, client/src/components/NavBar.jsx, client/src/components/approval/ApprovalList.jsx, client/src/components/posts/NewPost.jsx, client/src/managers/postManager.js
- Added new Route
- Added route to navbar
- Added in 'PostManager.js' two functions. One to return all unapproved posts, another to approve a post by Id
- Put the corresponding endpoints in the 'PostController' file.
- Put the pieces together to create a simple component to view unapproved posts and then click a button to approve
=> created a new component to view and approve unapproved posts

client/src/components/posts/NewPost.jsx
- Added the functionality to the 'NewPost' component to create a new post as initially unapproved unless the currently logged in
user is an admin.
=> new posts are now initially unapproved unless admin

client/src/components/posts/EditPost.css, client/src/components/posts/EditPost.jsx
- Completed and implemented CSS for the Edit Post view
=> Ft/css edit post/ezjbrewer

Controllers/TagController.cs, client/src/components/tags/TagsList.jsx, client/src/managers/tagManager.js
- created new controller to Delete a tag on `TagController.cs` page
- created getTag fetch call on `tagManager.js` page
- updated `TagList.jsx` page to import delete modal
=> completed delete task

client/src/components/Home.jsx, client/src/components/approval/Approval.css, client/src/components/approval/ApprovalList.jsx, client/src/components/categories/Category.css, client/src/components/categories/CategoryList.jsx, client/src/components/categories/EditCategory.jsx, client/src/components/categories/NewCategory.jsx, client/src/components/posts/CommentDetail.jsx, client/src/components/posts/CommentList.jsx, client/src/components/posts/EditComment.jsx, client/src/components/posts/MyPosts.jsx, client/src/components/posts/PostDetails.css, client/src/components/posts/PostDetails.jsx, client/src/components/posts/ViewPosts.css, client/src/components/posts/ViewPosts.jsx, client/src/components/reaction/Reaction.css, client/src/components/reaction/Reaction.jsx, client/src/components/tags/CreateTag.jsx, client/src/components/tags/EditTag.jsx, client/src/components/tags/Tags.css, client/src/components/tags/TagsList.jsx, client/src/components/userprofiles/ActviateAUserProfile.jsx, client/src/components/userprofiles/DeactviateAUserProfile.jsx, client/src/components/userprofiles/UserProfile.css, client/src/components/userprofiles/UserProfilesList.jsx
- Implemented consistent CSS across the whole application
=> Ft/css additions/ezjbrewer

client/src/components/userprofiles/UserProfileDetails.jsx
=> Implemented UserProfile CSS

client/src/components/posts/ViewPosts.jsx
###Changes to Navigation after unapprove /approve post
=> Ft/un approve post/swathi

client/src/components/NavBar.jsx
- Added navigation after the user decides to log out
=> Ft/logout hotfix/ezjbrewer

Controllers/UserProfileController.cs, Models/DTOs/UserProfileDTO.cs, client/src/components/ApplicationViews.jsx, client/src/components/userprofiles/EditUserProfile.css, client/src/components/userprofiles/EditUserProfile.jsx, client/src/components/userprofiles/UserProfileDetails.jsx, client/src/managers/userProfileManager.js
- User profile edit route added
- User profile edit component added
- User profile edit manager function added, as well as corresponding backend endpoint in userProfile controller
- Added basic css.
=> created a user profile edit page to change the role of a user. css added

client/src/components/posts/CommentList.jsx
=> Added condition for comment btn to render if user is an admin

client/src/components/posts/PostDetails.jsx
updated `PostDetails.jsx` so admin can delete any posts while users can only delete their own
=> resolved delete option for admin on all posts

Controllers/PostController.cs, Models/Post.cs, Utilities.cs, client/src/components/posts/EditPost.jsx, client/src/components/posts/MyPosts.jsx, client/src/components/posts/NewPost.jsx, client/src/components/posts/ViewPosts.jsx
#1 
###Changes
Estimated read time updated
###Files Changed
postController.cs
Utilities.cs
viewPost.jsx
MyPosts.jsx
EditPost.jsx
###Test
displaying estimated Read time
=> Ft/estimated read time/swathi

client/src/components/categories/NewCategory.jsx, client/src/components/posts/CommentList.jsx
=> Added 250 millisecond timer after category is posted
